project:
  type: website
  output-dir: docs
  
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


website:
  title: Najmeh Taleb
  
  navbar:
    left:
      - text: Overview 
        href: overview.qmd
        
      - text: Python Ecosystem
        href: https://najmehtaleb.github.io/python-ecosystem/
        
      - text: Machine Learning 
        href: https://najmehtaleb.github.io/machine-learning/
        
      - text: Math
        href: https://najmehtaleb.github.io/math-for-ml-dl
        


        
    right:
      - icon: github
        href: https://github.com/najmehtaleb
        
      - icon: twitter
        href: https://twitter.com/NajmehTaleb


execute:
  freeze: auto


