project:
  type: website
  output-dir: docs
  
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


website:
  title: "Najmeh Taleb"
  
  navbar:
    left:
      - text: Overview 
        href: index.qmd
      - text: "Math for ML"
        href: "https://najmehtaleb.github.io/math-for-ml-dl"
      - text: "About"
        href: about.qmd
        
    right:
      - icon: github
        href: "https://github.com/najmehtaleb"
      - icon: twitter
        href: "https://twitter.com/NajmehTaleb"


execute:
  freeze: auto


