project:
  type: website
  output-dir: docs
  
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


website:
  
  navbar:
    left:
      - text: Najmeh Taleb 
        href: overview.qmd
        
      - text: Machine Learning 
        href: https://najmehtaleb.github.io/machine-learning/
        
      - text: Math for ML-DL
        href: https://najmehtaleb.github.io/math-for-ml-dl
        
      - text: Reference
        
    right:
      - icon: github
        href: https://github.com/najmehtaleb
        
      - icon: twitter
        href: https://twitter.com/NajmehTaleb



